### ISSUE TITLE
Code changes necessary to be compatible with WooCommerce 3.0

### ISSUE THREAD

**Issue by theleemon** [hyyan/woo-poly-integration#137]
Hi!

I've created a text file with the changes that are needed to make the current plugin's code work with WooCommerce 3.0. I think I've fixed most of the code, but maybe there are some bugs left. I have no idea how to make a pull request, so if anyone is able it would be cool.

[woopoly-fixes.txt](https://github.com/hyyan/woo-poly-integration/files/945725/woopoly-fixes.txt)

Note: Line numbers in the doc are approximate

**Comment by theleemon** [comment]
More fixes:

src/Hyyan/WPI/Emails.php
================

(line 467)

`$order_language = pll_get_post_language($order->id, 'locale');`
to:
`$order_language = pll_get_post_language($order->get_id(), 'locale');`

(line 498)
`$replace['order-date'] = date_i18n(wc_date_format(), strtotime($order->order_date));`
to:
`$replace['order-date'] = date_i18n(wc_date_format(), strtotime($order->get_date_created()));`

**Comment by theleemon** [comment]
Another fix:

**File: src/Hyyan/WPI/Utilities.php**

(line 57)
`return static::getProductTranslationsArrayByID($product->id, $excludeDefault);`
to:
`return static::getProductTranslationsArrayByID($product->get_id(), $excludeDefault);`

**Comment by Jon007** [comment]
thanks for this, I'll take a look... many of these were fixed in the woocommerce2.7 branch so I'll try merging with that..

**Comment by SillyMe727** [comment]
Wow, thank you so much, @theleemon. This is brilliant. Did you test the compatibility with WC 3.0?

I am hoping for an update of this plugin soon. I would be happy to pay/ donate for it too.

**Comment by theleemon** [comment]
I tested it in a vanilla site with just WC and Polylang active, but not thoroughly, so there might be bugs still.

**Comment by theleemon** [comment]
I forgot to fix the Coupon.php file:

**src/Hyyan/WPI/Coupon.php**

(line 49)
`foreach ($coupon->product_ids as $id) {`
to:
`foreach ($coupon->get_product_ids() as $id) {`

(line 55)
`foreach ($coupon->exclude_product_ids as $id) {`
to:
`foreach ($coupon->get_excluded_product_ids() as $id) {			`

(line 62)
`foreach ($coupon->product_categories as $id) {`
to:
`foreach ($coupon->get_product_categories() as $id) {`

(line 69)
`foreach ($coupon->exclude_product_categories as $id) {`
to:
`foreach ($coupon->get_excluded_product_categories() as $id) {			`

(line 76)
```
$coupon->product_ids = $productIDS;
$coupon->exclude_product_ids = $excludeProductIDS;
$coupon->product_categories = $productCategoriesIDS;
$coupon->exclude_product_categories = $excludeProductCategoriesIDS;
```
to:  
```
$coupon->set_product_ids( $productIDS );
$coupon->set_excluded_product_ids( $excludeProductIDS );
$coupon->set_product_categories( $productCategoriesIDS );
$coupon->set_excluded_product_categories( $excludeProductCategoriesIDS );
```

**Comment by SillyMe727** [comment]
This is fantastic, thank you so much.

**Comment by Jon007** [comment]
Thanks, I've merging the 2.7 branch from December with more recent changes and proposals but now getting 
`Notice: Array to string conversion in wp-content/plugins/woocommerce/includes/wc-template-functions.php on line 1975`
Anyone seen that before?

**Comment by theleemon** [comment]
I've tested your fork:

https://github.com/Jon007/woo-poly-integration/tree/woocommerce2.7

but I'm not seeing those notices anywhere on the checkout page (even when selecting the US as a country). I'm seeing other bugs though that are fixed in my text doc (among them, the ones for the /Product/Stock.php file).

**Comment by Jon007** [comment]
Hold on, I haven't updated my fork yet..
those notices appeared to be due to a woocommerce language file not updated (only appeared when not in default language)

**Comment by theleemon** [comment]
Ooops, ok!

**Comment by Jon007** [comment]
ok, I've done an initial update on https://github.com/Jon007/woo-poly-integration
but lots of stuff I haven't tested yet..

**Comment by Jon007** [comment]
seems to be mostly working....
The checkout notice on each country value happens if you are (1) not logged in and (2) not using default language..

**Comment by theleemon** [comment]
Another fix:

**src/Hyyan/WPI/Utilities.php**

(line 262)
`$default_attributes = $product->get_variation_default_attributes();`
to:
`$default_attributes = $product->get_default_attributes();`

**Comment by Jon007** [comment]
yes, I saw that thanks, any other issues detected?

**Comment by Jon007** [comment]
Note there are a few changes left to do for backwards compatibility, in case someone updates woo-poly without updating wooCommmerce, I'll finish it over the weekend

**Comment by theleemon** [comment]
**src/Hyyan/WPI/Cart.php**

(line 294)
$variation_id = $variation->variation_id;
to:
$variation_id = $variation->get_id();

**Comment by theleemon** [comment]
**src/Hyyan/WPI/Reports.php**

(line 148)
`$data->product_id = $translation->id;`
to:
`$data->product_id = $translation->get_id();`

**Comment by Jon007** [comment]
got that, I've checked in these, a number of others and initial back-compatibiltiy in https://github.com/Jon007/woo-poly-integration

A large number of these changes are breaking to use with earlier version of wooCommerce so should have the back compatibility in, so worth checking a little more carefully before turning that fork into a pull request.

**Comment by Jon007** [comment]
Fixed in pull request 0.30RC1, the code is available at:
https://github.com/Jon007/woo-poly-integration

This should be treated as beta software until we have completed the testing, merge and release.

It would be great if you can test it!!!
If you find any issues with the RC, please report as separate issues, I will fix asap.
